### ISSUE TITLE
Navigation menu does not fit the height of the page on desktop, is this intentional?

### ISSUE THREAD

**Issue by Joepock123** [fac19/week1-hjrv#63]
If not, it can be changed by making the first line of the media query grid-template-areas (~line 181) 'nav title' instead of 'title title'

**Comment by HettieM** [comment]
Hi Joe! The idea with this is that we were going to put a background around the title, which would have taken up the empty space - but in interest of speed speed have heightened the bar as suggested. (Thanks for identifying line of code where I can do this!)
