### ISSUE TITLE
Use of *

### ISSUE THREAD

**Issue by Alexreid95** [fac19/week1-hjrv#69]
Might not be best practice to use * in the CSS stylesheet

**Comment by HettieM** [comment]
Hi, Renata, Kin, Gregor - would you be able to let us know whether this is the case? I haven't heard anything about this not being okay if you were trying to set a default for the page, obviously the specificity on this is incredibly low so can be overwritten with anything later on. If not best practice, please could you let us know how to do this. Thanks!

**Comment by Albadylic** [comment]
Hey! I'd suggest putting a tag on ```<body>``` or ```<html>``` if you want it to apply to the entire page.

If you want to avoid repeating CSS rules you can rely on inheritance: setting a rule on a parent will allow its children to inherit it. :family_woman_girl_boy: :baby: 

I'm not sure if this is *best* practice but I think it's less likely to cause conflicts. It's what I do on my [Portfolio site](https://github.com/Albadylic/albadylic.github.io/blob/master/style.css) :electric_plug:

**Comment by HettieM** [comment]
Thanks!! :)
